"""empty message

Revision ID: dfa82c02ab44
Revises: 
Create Date: 2024-07-07 10:52:24.140268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa82c02ab44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joke',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('show_name', sa.String(length=255), nullable=True),
    sa.Column('start_timestamp', sa.String(length=8), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('video_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joke')
    # ### end Alembic commands ###
